apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlopsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlopsapp
  template:
    metadata:
      labels:
        app: mlopsapp
    spec:
      containers:
      - name: mlopsapp
        image: us-central1-docker.pkg.dev/airy-semiotics-465715-j3/mlopsapp/mlopsapp:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlopsapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
