version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: machine-executor
    steps:
      - checkout

  build_docker_image:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcpkey.json
            gcloud auth activate-service-account --key-file=gcpkey.json
            gcloud auth configure-docker us-central1-docker.pkg.dev
      - run:
          name: Build and Push Docker Image
          command: |
            docker --version
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest

  deploy_to_gke:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev
      - run:
          name: Configure GKE Cluster
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID
      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f kubernetes_dev.yaml

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image
